### ISSUE TITLE
Wrong pom version

### ISSUE THREAD

**Issue by zemoa** [123Haynes/libsass-maven-plugin#2]
Hello,

When I try to build my project I got this issue:
[WARNING] Failed to retrieve plugin descriptor for com.gitlab.haynes:libsass-maven-plugin:0.2.23: Invalid plugin descriptor for com.gitlab.haynes:libsass-maven-plugin:0.2.23 (.../repository/com/gitlab/haynes/libsass-maven-plugin/0.2.23/libsass-maven-plugin-0.2.23.jar), Plugin's descriptor contains the wrong version: 0.2.24-SNAPSHOT

Seems like the version in the POM is not corresponding to the version declared in maven repo.

**Comment by 123Haynes** [comment]
@zemoa I can't reproduce this. I also checked the pom inside the 0.2.23 jar on maven central and it also contains 0.2.23 as the version number.

Can you provide a small example project where you experience this?

**Comment by zemoa** [comment]
Actually I got this artifact through my nexus. And it seems that on this Nexus, the jar contains wrong version. 
I don't understand how this is possible.
So I think this is not an issue linked to your library...

Thanks!
